[program:nmba-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /home/username/public_html/artisan queue:work database --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=username
numprocs=5
redirect_stderr=true
stdout_logfile=/home/username/public_html/storage/logs/worker.log
stopwaitsecs=3600
